// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgXG2cwXGDvj8XEckMHHznw-EOcBAC6aA',
    appId: '1:220005612030:web:6bc2ff95e46fa1245f28af',
    messagingSenderId: '220005612030',
    projectId: 'dobiku-app-1b86f',
    authDomain: 'dobiku-app-1b86f.firebaseapp.com',
    storageBucket: 'dobiku-app-1b86f.firebasestorage.app',
    measurementId: 'G-K2JZ3WD1K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZWsdMnoKPIQXxvVqTNqUUEzRRe5f5Qo',
    appId: '1:220005612030:android:113e355a403f7bcb5f28af',
    messagingSenderId: '220005612030',
    projectId: 'dobiku-app-1b86f',
    storageBucket: 'dobiku-app-1b86f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Xj__ti7Xqq8iMl-ylfuobitFK3gV8c4',
    appId: '1:220005612030:ios:c5efe60fec89a3de5f28af',
    messagingSenderId: '220005612030',
    projectId: 'dobiku-app-1b86f',
    storageBucket: 'dobiku-app-1b86f.firebasestorage.app',
    iosBundleId: 'com.example.dobikuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Xj__ti7Xqq8iMl-ylfuobitFK3gV8c4',
    appId: '1:220005612030:ios:c5efe60fec89a3de5f28af',
    messagingSenderId: '220005612030',
    projectId: 'dobiku-app-1b86f',
    storageBucket: 'dobiku-app-1b86f.firebasestorage.app',
    iosBundleId: 'com.example.dobikuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgXG2cwXGDvj8XEckMHHznw-EOcBAC6aA',
    appId: '1:220005612030:web:0799d7114f0476e85f28af',
    messagingSenderId: '220005612030',
    projectId: 'dobiku-app-1b86f',
    authDomain: 'dobiku-app-1b86f.firebaseapp.com',
    storageBucket: 'dobiku-app-1b86f.firebasestorage.app',
    measurementId: 'G-HCG39WXVL0',
  );

}